version: '3.9'

services:
  discovery-server:
    image: ${DISCOVERY_IMAGE}
    ports:
      - "${DISCOVERY_SERVER_PORT}:8761"
    environment:
      EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
    networks:
      - ecommerce-network

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "${ZIPKIN_PORT}:9411"
    networks:
      - ecommerce-network

  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:${VAULT_PORT}
    cap_add:
      - IPC_LOCK
    command: server -dev
    ports:
      - "${VAULT_PORT}:8200"
    networks:
      - ecommerce-network

  vault-init:
    image: vault:1.13.3
    depends_on:
      - vault
    volumes:
      - ./scripts/vault-init.sh:/vault-init.sh
    entrypoint: ["sh", "/vault-init.sh"]
    networks:
      - ecommerce-network

  config-server:
    image: ${CONFIG_IMAGE}
    depends_on:
      - discovery-server
      - vault
      - rabbit-mq
    environment:
      VAULT_HOST: ${VAULT_HOST}
      VAULT_PORT: ${VAULT_PORT}
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    networks:
      - ecommerce-network

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - ecommerce-network

  gateway-server:
    image: ${GATEWAY_IMAGE}
    depends_on:
      - discovery-server
      - redis
      - zipkin
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
      - ecommerce-network

  product-service:
    image: ${PRODUCT_IMAGE}
    depends_on:
      - discovery-server
      - config-server
      - gateway-server
      - zipkin
      - rabbit-mq
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./scripts/wait-for-config.sh:/wait-for-config.sh
    entrypoint: ["/bin/sh", "/wait-for-config.sh"]
    ports:
      - "${PRODUCT_PORT}:8081"
    networks:
      - ecommerce-network

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_UI_PORT}:15672"
      - "${RABBITMQ_AMQP_PORT}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - ecommerce-network

  order-service:
    image: ${ORDER_IMAGE}
    depends_on:
      - discovery-server
      - config-server
      - gateway-server
      - zipkin
      - rabbit-mq
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      CONFIG_SERVER_HEALTH_URL: ${CONFIG_SERVER_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      EUREKA_URL: ${EUREKA_URL}
    volumes:
      - ./scripts/wait-for-config.sh:/wait-for-config.sh
    entrypoint: ["/bin/sh", "/wait-for-config.sh"]
    ports:
      - "${ORDER_PORT}:8082"
    networks:
      - ecommerce-network

  notification-service:
    image: ${NOTIFICATION_IMAGE}
    depends_on:
      - discovery-server
      - config-server
      - gateway-server
      - zipkin
      - rabbit-mq
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./scripts/wait-for-config.sh:/wait-for-config.sh
    entrypoint: ["/bin/sh", "/wait-for-config.sh"]
    ports:
      - "${NOTIFICATION_PORT}:8083"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
