server:
  port: 8081

spring:
  application:
      name: product-service
      
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
    
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true